# Generated by Django 3.1.2 on 2020-11-19 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Surname', models.CharField(max_length=45)),
                ('PhoneNumber', models.CharField(max_length=45)),
                ('PESEL', models.CharField(max_length=45)),
                ('CompanyName', models.CharField(max_length=45)),
                ('CompanyAdress', models.CharField(max_length=45)),
                ('AccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmaksiegowa.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PIT',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases_Sales',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=45)),
                ('NetAmount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('GrossAmount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('CurrencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmaksiegowa.currency')),
                ('DocumentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmaksiegowa.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('ClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmaksiegowa.client')),
                ('DocumentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmaksiegowa.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Declarations',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.CharField(max_length=45)),
                ('Department', models.CharField(max_length=45)),
                ('DateFrom', models.DateTimeField()),
                ('DateTo', models.DateTimeField()),
                ('DocumentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmaksiegowa.purchases_sales')),
                ('PIT_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmaksiegowa.pit')),
            ],
        ),
    ]
