# Generated by Django 3.1.3 on 2020-11-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Surname', models.CharField(max_length=45)),
                ('PhoneNumber', models.CharField(max_length=45)),
                ('PESEL', models.CharField(max_length=45)),
                ('CompanyName', models.CharField(max_length=45, null=True)),
                ('CompanyAddress', models.CharField(max_length=45, null=True)),
                ('NIP', models.CharField(max_length=45, null=True)),
                ('REGON', models.CharField(max_length=45, null=True)),
                ('AccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrBiuroKsiegowe.account')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('ClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrBiuroKsiegowe.client')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PIT',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Tax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchasesSales',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=45)),
                ('NetAmount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('GrossAmount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Tax', models.IntegerField()),
                ('CurrencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrBiuroKsiegowe.currency')),
                ('DocumentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrBiuroKsiegowe.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='DocumentTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrBiuroKsiegowe.documenttype'),
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Ammount', models.CharField(max_length=45)),
                ('Department', models.CharField(max_length=45)),
                ('DateFrom', models.DateTimeField()),
                ('DateTo', models.DateTimeField()),
                ('DocumentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrBiuroKsiegowe.document')),
                ('PIT_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrBiuroKsiegowe.pit')),
            ],
        ),
    ]
