# Generated by Django 3.1.3 on 2020-12-18 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrBiuroKsiegowe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('Name', 'Surname')},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('Name',)},
        ),
        migrations.AlterModelOptions(
            name='declaration',
            options={'ordering': ('DateFrom', 'DateTo')},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('Date',)},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ('Type',)},
        ),
        migrations.AlterModelOptions(
            name='pit',
            options={'ordering': ('Name',)},
        ),
        migrations.AlterModelOptions(
            name='purchasessales',
            options={'ordering': ('ProductName',)},
        ),
        migrations.RemoveField(
            model_name='client',
            name='AccountId',
        ),
        migrations.AddField(
            model_name='client',
            name='User',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='Clients', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='ClientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mrBiuroKsiegowe.client'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
