# Generated by Django 3.1.3 on 2020-12-18 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrBiuroKsiegowe', '0002_auto_20201218_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='CreatedBy',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='DocumentCreatedBy', to='auth.user'),
            preserve_default=False,
        ),
    ]
