# Generated by Django 3.1.3 on 2021-01-08 12:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Surname', models.CharField(max_length=45)),
                ('PhoneNumber', models.CharField(max_length=45)),
                ('PESEL', models.CharField(max_length=45)),
                ('CompanyName', models.CharField(max_length=45, null=True)),
                ('CompanyAddress', models.CharField(max_length=45, null=True)),
                ('NIP', models.CharField(max_length=45, null=True)),
                ('REGON', models.CharField(max_length=45, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('Name', 'Surname'),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Code', models.CharField(max_length=45)),
                ('Country', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CreationDate', models.DateTimeField(default=datetime.datetime(2021, 1, 8, 13, 41, 6, 183116))),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Documents', to='BiuroKsiegowe.client')),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DocumentCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('CreationDate',),
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ('Type',),
            },
        ),
        migrations.CreateModel(
            name='PIT',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Desc', models.TextField(default=None)),
                ('Deadline', models.CharField(default=None, max_length=255)),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='PurchasesSales',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=45)),
                ('NetAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GrossAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tax', models.IntegerField()),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BiuroKsiegowe.currency')),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BiuroKsiegowe.document')),
            ],
            options={
                'ordering': ('ProductName',),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='DocumentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BiuroKsiegowe.documenttype'),
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Desc', models.TextField(default=None)),
                ('Amount', models.CharField(max_length=45)),
                ('Department', models.CharField(max_length=45)),
                ('DateFrom', models.DateTimeField()),
                ('DateTo', models.DateTimeField()),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BiuroKsiegowe.document')),
                ('PIT', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BiuroKsiegowe.pit')),
            ],
            options={
                'ordering': ('DateFrom', 'DateTo'),
            },
        ),
    ]
